version: "2"
linters:
  default: all
  disable:
    - copyloopvar
    - cyclop
    - depguard
    - dogsled
    - dupword
    - exhaustruct
    - forbidigo
    - ginkgolinter
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - grouper
    - importas
    - ireturn
    - makezero
    - mnd
    - noctx
    - nonamedreturns
    - testableexamples
    - testifylint
    - testpackage
    - unparam
    - zerologlint
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 100
      statements: 50
      ignore-comments: true
    lll:
      line-length: 140
      tab-width: 1
    nlreturn:
      block-size: 2
    varnamelen:
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
      ignore-decls:
        - n int
        - x int
        - y int
        - z int
        - i int
        - a int
        - r int
        - g int
        - b int
        - r int64
        - g int64
        - b int64
        - c int
        - j int
        - T any
        - a any
        - b any
        - c any
        - d any
        - data any
        - n any
        - ch chan T
        - ch chan int
        - ch chan any
        - wg sync.WaitGroup
        - t time.Time
        - f func()
        - f func(T)
        - cb func()
        - t testing.T
        - b testing.B
        - sb strings.Builder
    wsl:
      force-case-trailing-whitespace: 3
      allow-cuddle-declarations: true
      force-err-cuddling: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - funlen
          - gochecknoglobals
          - noctx
        path: _test(_[^/]+)?\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
